maintainer        "CrowdMob Inc."
maintainer_email  "developers@crowdmob.com"
license           "Apache 2.0"
description       "SCM checkout, bundle install, and restart Sinatra web applications (relies on aws-opsworks/deploy)."
depends           "deploy"
recipe            "sinatra::configure"
recipe            "sinatra::deploy"